apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: keep-one-backup
  namespace: longhorn-system
spec:
  cron: "0 2 * * *" # Runs nightly at 2:00 AM
  task: "backup"   # Ships data to your defined external target
  groups:
  - default        # Automatically snapshots all default volumes
  retain: 1        # Deletes the previous backup, retaining only the latest 1
