apiVersion: apps/v1
kind: Deployment
metadata:
  name: frpc
  namespace: frpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      nodeSelector:
        node-role.kubernetes.io/control-plane: ""

      containers:
        - name: frpc
          image: fatedier/frpc:v0.60.0
          # Explicitly tell frpc to look for the YAML file format
          args: ["-c", "/etc/frp/frpc.yaml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/frp
      volumes:
        - name: config-volume
          configMap:
            name: frpc-config
