apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      version: "2.2.12"  # <-- Exact chart version mapping to the latest image
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  upgrade:
    remediation:
      retries: 3
  install:
    createNamespace: false
  targetNamespace: stakater-reloader
  interval: 1h
  values:
    reloader:
      watchGlobally: true
