apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical-helm-charts
  namespace: infisical
spec:
  interval: 2h0m0s
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
