apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic-app
  template:
    metadata:
      labels:
        app: generic-app
    spec:
      containers:
        - name: generic-app
          image: generic-app # Placeholder tag, overridden by Kustomize images section
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: generic-app
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: generic-app
