apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: renovate-static-sync
  namespace: renovate
spec:
  infisicalAuthRef:
    name: renovate-infisical-auth
  sources:
    - projectSlug: misti-usiu-big-data-s-j-ea
      environmentSlug: prod
      secretPath: /
  targets:
    - name: renovate-config-files # Materializes the ConfigMap
      kind: ConfigMap
    - name: renovate-secret       # Materializes the Secret
      kind: Secret
