apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: infisical-connection
  namespace: renovate
spec:
  address: https://infisical.sazara.co.ke
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: renovate-infisical-auth
  namespace: renovate
spec:
  connectionRef:
    name: infisical-connection
  universalAuth:
    secretsRef:
      secretName: infisical-machine-identity-credentials
