apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: infisical-connection
  namespace: renovate
spec:
  address: https://infisical.sazara.co.ke
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: renovate-infisical-auth
  namespace: renovate
spec:
  infisicalConnectionRef: # Fixed: Name updated in v1beta1
    name: infisical-connection
    namespace: renovate
  method: universal         # Fixed: Added explicit method block
  universal:
    clientIdRef:
      name: infisical-machine-identity-credentials
      key: clientId
      namespace: renovate
    clientSecretRef:
      name: infisical-machine-identity-credentials
      key: clientSecret
      namespace: renovate
