# Handles all configuration files (config.js)
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalStaticSecret
metadata:
  name: renovate-config-files-sync
  namespace: renovate
spec:
  authenticationRef:
    name: renovate-infisical-auth
  authenticationStrategy: universalAuth
  source:
    projectSlug: misti-usiu-big-data-s-j-ea
    environmentSlug: prod
    secretsPath: /
  managedConfigMap:
    configMapName: renovate-config-files # Matched to Deployment volumes
  transforms:
    - autoRename:
        regex: "^renovate-(.*)"
        substitution: "$1"
---
# Handles all credentials and environment keys
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalStaticSecret
metadata:
  name: renovate-credentials-sync
  namespace: renovate
spec:
  authenticationRef:
    name: renovate-infisical-auth
  authenticationStrategy: universalAuth
  source:
    projectSlug: misti-usiu-big-data-s-j-ea
    environmentSlug: prod
    secretsPath: /
  managedSecret:
    secretName: renovate-secret # Matched to Deployment envFrom/secretRef
    secretType: Opaque
  transforms:
    - autoRename:
        regex: "^renovate-(.*)"
        substitution: "$1"
