apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: renovate-static-sync
  namespace: renovate
spec:
  infisicalAuthRef:
    name: renovate-infisical-auth
    namespace: renovate

  syncOptions:
    refreshInterval: 5m

  sources:
    - projectSlug: misti-usiu-big-data-s-j-ea
      environmentSlug: prod
      secretPath: /

  targets:
    - name: renovate-config-files
      namespace: renovate
      kind: ConfigMap
      creationPolicy: Owner

    - name: renovate-secret
      namespace: renovate
      kind: Secret
      creationPolicy: Owner
