apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/renovate
  - infisical-auth.yaml
  - infisical-secrets.yaml


images:
  - name: renovate
    newName: mend/renovate-ce
    newTag: 14.8.0-full
