apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/generic-app

images:
  - name: generic-app
    newName: ghcr.io/your-org/generic-app # This is updated dynamically by the promotion pipeline
    newTag: placeholder # Replaced with actual sha tag on build promotion
