apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h0m0s
  retryInterval: 2m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/opacs/metrics-server
  prune: true
  wait: true
