apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 20Gi
