apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/linkding  # Traverses out of opacs up to base/linkding


images:
  - name: linkding
    newName: sissbruecker/linkding
    newTag: 1.45.0
